version: '2'

services:

  ecodatum-server:
    build:
      context: ./
      args:
        CIPER_KEY: $CIPER_KEY
        MYSQL_PASSWORD: $MYSQL_PASSWORD
    image: kwingerden/ecodatum-server:1.0
    networks:
      - public-network
      - private-network
    ports:
      - "8080:8080"
    volumes:
      - shared-volume:/shared-volume
    depends_on:
      - ecodatum-database

  ecodatum-database:
    image: mdillon/postgis:10
    networks:
      - private-network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ecodatum-database:/var/lib/postgresql/data
      - shared-volume:/shared-volume
    restart: always

volumes:

  ecodatum-database:
  shared-volume:

networks:

  public-network:
    driver: bridge

  private-network:
    driver: bridge
