version: '2'

services:

  ecodatum-server:
    build:
      context: ./
      args:
        CIPER_KEY: $CIPER_KEY
        MYSQL_PASSWORD: $MYSQL_PASSWORD
    image: kwingerden/ecodatum-server:1.0
    networks:
      - public-network
      - private-network
    ports:
      - "8080:8080"
    volumes:
      - shared-volume:/shared-volume
    restart: always
    depends_on:
      - ecodatum-database

  ecodatum-database:
    image: mysql:5.7.20
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - private-network
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - ecodatum-database:/var/lib/mysql
      - shared-volume:/shared-volume
    restart: always

volumes:

  ecodatum-database:
  shared-volume:

networks:

  public-network:
    driver: bridge

  private-network:
    driver: bridge
